version: "3.9"

services:
  postgres-balance:
    image: postgres
    environment:
      POSTGRES_DB: "dealdb"
      POSTGRES_USER: "dealuser"
      POSTGRES_PASSWORD: "dealpassword"
    ports:
      - 7432:5432