version: "3"

services:
  trading:
    image: postgres
    environment:
      POSTGRES_DB: "dealdb"
      POSTGRES_USER: "dealuser"
      POSTGRES_PASSWORD: "dealpassword"
    ports:
      - 7432:5432

  flyway:
    image: flyway/flyway:latest
    command: ["-url=jdbc:postgresql://trading:5432/dealdb", "-user=dealuser", "-password=dealpassword", "migrate"]
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - trading