// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/artnikel/TradingService/proto"
)

// TradingServiceClient is an autogenerated mock type for the TradingServiceClient type
type TradingServiceClient struct {
	mock.Mock
}

// ClosePosition provides a mock function with given fields: ctx, in, opts
func (_m *TradingServiceClient) ClosePosition(ctx context.Context, in *proto.ClosePositionRequest, opts ...grpc.CallOption) (*proto.ClosePositionResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.ClosePositionResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ClosePositionRequest, ...grpc.CallOption) *proto.ClosePositionResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ClosePositionResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.ClosePositionRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPrices provides a mock function with given fields: ctx, in, opts
func (_m *TradingServiceClient) GetPrices(ctx context.Context, in *proto.GetPricesRequest, opts ...grpc.CallOption) (*proto.GetPricesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.GetPricesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetPricesRequest, ...grpc.CallOption) *proto.GetPricesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetPricesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetPricesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfit provides a mock function with given fields: ctx, in, opts
func (_m *TradingServiceClient) GetProfit(ctx context.Context, in *proto.GetProfitRequest, opts ...grpc.CallOption) (*proto.GetProfitResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.GetProfitResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetProfitRequest, ...grpc.CallOption) *proto.GetProfitResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetProfitResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetProfitRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnclosedPositions provides a mock function with given fields: ctx, in, opts
func (_m *TradingServiceClient) GetUnclosedPositions(ctx context.Context, in *proto.GetUnclosedPositionsRequest, opts ...grpc.CallOption) (*proto.GetUnclosedPositionsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.GetUnclosedPositionsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetUnclosedPositionsRequest, ...grpc.CallOption) *proto.GetUnclosedPositionsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetUnclosedPositionsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetUnclosedPositionsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTradingServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewTradingServiceClient creates a new instance of TradingServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTradingServiceClient(t mockConstructorTestingTNewTradingServiceClient) *TradingServiceClient {
	mock := &TradingServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
